# Generated by Django 5.2.6 on 2025-09-22 10:47

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contacts",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("country", models.CharField(max_length=20, verbose_name="Страна")),
                ("city", models.CharField(max_length=20, verbose_name="Город")),
                ("street", models.CharField(max_length=30, verbose_name="Улица")),
                ("house_number", models.CharField(max_length=10, verbose_name="Номер дома")),
            ],
            options={
                "verbose_name": "Контакт",
                "verbose_name_plural": "Контакты",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50, verbose_name="Название")),
                ("model", models.CharField(max_length=50, verbose_name="Модель")),
                (
                    "release_date",
                    models.DateTimeField(
                        default=datetime.datetime(2025, 9, 22, 13, 47, 45, 829380),
                        verbose_name="Дата выхода продукта на рынок",
                    ),
                ),
            ],
            options={
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
                "ordering": ["release_date"],
            },
        ),
        migrations.CreateModel(
            name="Node",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50, verbose_name="Название")),
                ("level", models.IntegerField(verbose_name="Уровень иерархии")),
                (
                    "debt",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name="Задолженность"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Время создания")),
                (
                    "contacts",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="store.contacts", verbose_name="Контакты"
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="store.node",
                        verbose_name="Поставщик",
                    ),
                ),
                ("products", models.ManyToManyField(to="store.product", verbose_name="Продукты")),
            ],
            options={
                "verbose_name": "Поставщик",
                "verbose_name_plural": "Поставщики",
                "ordering": ["created_at"],
            },
        ),
    ]
