# Generated by Django 5.2.6 on 2025-09-22 12:39

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="node",
            name="level",
            field=models.IntegerField(
                choices=[(0, "Завод"), (1, "Розничная сеть"), (2, "Индивидуальный предприниматель")],
                verbose_name="Уровень иерархии",
            ),
        ),
        migrations.AlterField(
            model_name="node",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="store.node",
                verbose_name="Поставщик",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="release_date",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 9, 22, 15, 39, 30, 677415),
                verbose_name="Дата выхода продукта на рынок",
            ),
        ),
    ]
