# Generated by Django 5.2.6 on 2025-09-26 17:18

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_alter_node_level_alter_node_supplier_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contacts",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="node",
            name="level",
            field=models.IntegerField(
                blank=True,
                choices=[(0, "Завод"), (1, "Розничная сеть"), (2, "Индивидуальный предприниматель")],
                null=True,
                verbose_name="Уровень иерархии",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="release_date",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 9, 26, 20, 18, 0, 632812), verbose_name="Дата выхода продукта на рынок"
            ),
        ),
    ]
