# Generated by Django 5.2.6 on 2025-09-26 17:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_alter_contacts_email_alter_node_level_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="release_date",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 9, 26, 20, 35, 1, 489887), verbose_name="Дата выхода продукта на рынок"
            ),
        ),
    ]
