# Generated by Django 5.2.6 on 2025-09-26 18:32

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_alter_product_release_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="release_date",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 9, 26, 21, 32, 22, 929075),
                verbose_name="Дата выхода продукта на рынок",
            ),
        ),
    ]
